<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="Yeteendra" failures="0" tests="1" name="Default test" time="0.084" errors="0" timestamp="2024-02-18T15:01:43 IST">
  <testcase classname="com.selenium.automation.resorces.BaseTest" name="@BeforeSuite Beforesuit" time="0.07">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	VERSION_2_3_29 cannot be resolved or is not a field
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
VERSION_2_3_29 cannot be resolved or is not a field

at com.aventstack.extentreports.reporter.BasicFileReporter.start(BasicFileReporter.java:98)
at com.aventstack.extentreports.ReportObservable.register(ReportObservable.java:191)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:82)
at com.selenium.automation.resorces.BaseTest.Beforesuit(BaseTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite Beforesuit -->
  <testcase classname="com.selenium.automation.resorces.BaseTest" name="@BeforeTest launch_application" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeTest launch_application -->
  <testcase classname="com.selenium.automation.application_login_test" name="@BeforeMethod basicSetup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod basicSetup -->
  <testcase classname="com.selenium.automation.application_login_test" name="@AfterMethod tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="com.selenium.automation.application_login_test" name="login_page_url_test" time="0.0">
    <skipped/>
  </testcase> <!-- login_page_url_test -->
  <testcase classname="com.selenium.automation.application_login_test" name="login_with_invalid_password" time="0.0">
    <ignored/>
  </testcase> <!-- login_with_invalid_password -->
  <testcase classname="com.selenium.automation.application_login_test" name="login_with_blank_username_and_password" time="0.0">
    <ignored/>
  </testcase> <!-- login_with_blank_username_and_password -->
  <testcase classname="com.selenium.automation.application_login_test" name="login_page_tile_test" time="0.0">
    <ignored/>
  </testcase> <!-- login_page_tile_test -->
  <testcase classname="com.selenium.automation.application_login_test" name="log_in_with_invalid_credentials" time="0.0">
    <ignored/>
  </testcase> <!-- log_in_with_invalid_credentials -->
  <testcase classname="com.selenium.automation.application_login_test" name="sign_in_withCredential" time="0.0">
    <ignored/>
  </testcase> <!-- sign_in_withCredential -->
</testsuite> <!-- Default test -->
